import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/site/site-header";
import { SiteFooter } from "@/components/site/site-footer";
import { services } from "@/config/services";
import { assetPath } from "@/lib/asset-path";

export const metadata: Metadata = { title: "Interior Design Services", description: "Full-home interiors, kitchens, wardrobes, furniture, lighting and execution." };
export default function ServicesPage() { return <main><SiteHeader /><section className="px-5 pb-24 pt-20 sm:px-9 lg:px-12 lg:pt-28"><div className="mx-auto max-w-[1500px]"><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="text-sm text-[#7a6a5e]">Complete interior design</p><h1 className="mt-6 font-display text-[clamp(4.5rem,9vw,9rem)] leading-[.84] tracking-[-.055em]">One vision,<br />every detail.</h1></div><p className="max-w-lg text-lg leading-8 text-[#66594f]">From the first plan to the final fitting, one integrated team keeps design intent, budget and site decisions connected.</p></div><div className="mt-16 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="relative aspect-[4/5] overflow-hidden lg:sticky lg:top-8"><Image src={assetPath("/images/kitchen.png")} alt="Detailed kitchen joinery and stone island" fill sizes="45vw" className="object-cover" /></div><div className="border-t border-[#8f7f70]">{services.map((service) => <div key={service.name} className="grid gap-3 border-b border-[#cbb9a6] py-7 sm:grid-cols-[60px_1fr_1.3fr]"><span className="text-xs text-[#9a897b]">{service.number}</span><h2 className="font-display text-3xl">{service.name}</h2><p className="leading-7 text-[#6c5e53]">{service.copy}</p></div>)}</div></div><div className="mt-20 bg-[#a44928] p-8 text-white sm:p-12 lg:flex lg:items-center lg:justify-between"><h2 className="font-display text-5xl">Tell us what your home needs.</h2><Link href="/start-project" className="mt-7 inline-block border border-white/70 px-6 py-4 text-sm lg:mt-0">Start your project</Link></div></div></section><SiteFooter /></main>; }
