import type { Metadata } from "next";
import Link from "next/link";
import { auth } from "@/auth";
import { SiteHeader } from "@/components/site/site-header";
import { SiteFooter } from "@/components/site/site-footer";
import { GoogleSignin } from "@/components/forms/google-signin";
import { SignoutButton } from "@/components/forms/signout-button";
import { projectRepository } from "@/lib/repositories/projectRepository";
import { isGoogleDataConfigured } from "@/lib/google/sheets";

export const metadata: Metadata = { title: "Your Account", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function AccountPage(){const session=await auth();if(!session?.user?.email||!session.user.id)return <main><SiteHeader/><section className="grid min-h-[68vh] place-items-center px-5"><div className="max-w-md text-center"><p className="text-sm text-[#7a6a5e]">Your account</p><h1 className="mt-4 font-display text-6xl">Sign in to continue.</h1><p className="mt-5 leading-7 text-[#66594f]">Your estimates and project enquiries are private to your Google account.</p><div className="mt-8"><GoogleSignin configured={Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET)}/></div></div></section><SiteFooter/></main>;
let projects:Record<string,string>[]=[];let dataError="";if(isGoogleDataConfigured()){try{projects=await projectRepository.getByUser(session.user.id,session.user.email)}catch{dataError="We could not load your projects right now."}}
return <main><SiteHeader/><section className="px-5 pb-24 pt-16 sm:px-9 lg:px-12 lg:pt-24"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col gap-6 border-b border-[#a99380] pb-10 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[#7a6a5e]">Your account</p><h1 className="mt-3 font-display text-6xl sm:text-7xl">Welcome, {session.user.name?.split(" ")[0]||"home lover"}.</h1><p className="mt-3 text-[#66594f]">{session.user.email}</p></div><SignoutButton/></div><div className="mt-14 flex items-center justify-between"><h2 className="font-display text-4xl">My projects</h2><Link href="/start-project" className="bg-[#1b100c] px-5 py-3 text-sm text-white">Start a new project</Link></div>{dataError&&<p className="mt-8 border border-[#a44928] p-4 text-sm text-[#7a351f]">{dataError}</p>}{!isGoogleDataConfigured()&&<div className="mt-8 border border-[#b49d89] bg-[#e7d9cc] p-5"><p className="font-display text-2xl">Your project space is ready.</p><p className="mt-2 text-sm leading-6 text-[#66594f]">Google Sheets access needs to be configured before live projects can appear here.</p></div>}{projects.length?<div className="mt-8 border-t border-[#8e7d6f]">{projects.map((project)=><Link href={`/account/projects/${project.Project_ID}`} key={project.Project_ID} className="grid gap-3 border-b border-[#cbb9a6] py-6 sm:grid-cols-[1.1fr_1fr_1fr_1fr_auto] sm:items-center"><div><p className="font-display text-2xl">{project.Project_ID}</p><p className="mt-1 text-sm text-[#7a6a5e]">{project.Submitted_At?new Date(project.Submitted_At).toLocaleDateString("en-IN"):"Draft"}</p></div><p>{project.BHK} {project.Property_Type}</p><p>{project.City}</p><p>{project.Budget}</p><span className="justify-self-start border border-[#9c8877] px-3 py-2 text-sm">{project.Status}</span></Link>)}</div>:isGoogleDataConfigured()&&!dataError?<div className="mt-8 border border-dashed border-[#a99380] p-10 text-center"><p className="font-display text-3xl">No submitted projects yet.</p><p className="mt-3 text-[#66594f]">Your saved project will appear here after submission.</p></div>:null}</div></section><SiteFooter/></main>}
