import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { auth } from "@/auth";
import { SiteHeader } from "@/components/site/site-header";
import { SiteFooter } from "@/components/site/site-footer";
import { projectRepository } from "@/lib/repositories/projectRepository";

export const metadata:Metadata={title:"Project details",robots:{index:false,follow:false}};export const dynamic="force-dynamic";
export default async function AccountProjectPage({params}:{params:Promise<{id:string}>}){const session=await auth();if(!session?.user?.id||!session.user.email)return <main><SiteHeader/><section className="grid min-h-[65vh] place-items-center"><div className="text-center"><h1 className="font-display text-6xl">Sign in to view this project.</h1><Link href="/signin" className="mt-8 inline-block bg-[#1b100c] px-6 py-4 text-sm text-white">Sign in</Link></div></section></main>;const project=await projectRepository.getById((await params).id);if(!project||(project.User_ID!==session.user.id&&project.Email.toLowerCase()!==session.user.email.toLowerCase()))notFound();const rows=[["Home",`${project.BHK} ${project.Property_Type}`],["Location",`${project.Locality}, ${project.City}`],["Carpet area",`${project.Carpet_Area} sq ft`],["Spaces",project.Rooms],["Style",project.Styles],["Priorities",project.Priorities],["Budget",project.Budget],["Timeline",project.Timeline],["Preferred contact",`${project.Preferred_Contact} · ${project.Preferred_Time}`]];return <main><SiteHeader/><section className="px-5 pb-24 pt-16 sm:px-9 lg:px-12 lg:pt-24"><div className="mx-auto max-w-5xl"><Link href="/account" className="text-sm underline underline-offset-4">Back to account</Link><div className="mt-8 flex flex-col gap-5 border-b border-[#a99380] pb-10 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[#7a6a5e]">Project reference</p><h1 className="mt-2 font-display text-6xl">{project.Project_ID}</h1></div><span className="self-start border border-[#9c8877] px-4 py-3 text-sm">{project.Status}</span></div><div className="mt-12 grid gap-x-12 gap-y-7 sm:grid-cols-2">{rows.map(([label,value])=><div key={label} className="border-t border-[#cbb9a6] pt-4"><p className="text-sm text-[#7a6a5e]">{label}</p><p className="mt-2 text-lg">{value||"—"}</p></div>)}</div>{project.Notes&&<div className="mt-10 border-t border-[#cbb9a6] pt-4"><p className="text-sm text-[#7a6a5e]">Notes</p><p className="mt-3 max-w-3xl leading-7">{project.Notes}</p></div>}<div className="mt-14 bg-[#1b100c] p-8 text-white"><h2 className="font-display text-4xl">What happens next</h2><ol className="mt-6 space-y-3 text-white/70"><li>1. We review your requirements</li><li>2. A designer contacts you</li><li>3. Your consultation is scheduled</li></ol></div></div></section><SiteFooter/></main>}
